# Generated by Django 4.1 on 2022-08-09 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuizoPedia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercredential',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usercredential',
            name='userFirstName',
            field=models.CharField(default=None, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usercredential',
            name='userLastName',
            field=models.CharField(default=None, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usercredential',
            name='userPhone',
            field=models.CharField(default=None, max_length=11),
            preserve_default=False,
        ),
    ]
