# Generated by Django 4.1 on 2022-08-09 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuizoPedia', '0002_usercredential_created_usercredential_userfirstname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercredential',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='usercredential',
            name='userEmail',
            field=models.CharField(default=None, max_length=40),
        ),
        migrations.AlterField(
            model_name='usercredential',
            name='userFirstName',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='usercredential',
            name='userLastName',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='usercredential',
            name='userPassword',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='usercredential',
            name='userPhone',
            field=models.CharField(default=None, max_length=11),
        ),
    ]
