# Generated by Django 4.1 on 2022-08-11 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuizoPedia', '0003_alter_usercredential_created_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercredential',
            name='userId',
        ),
        migrations.AlterField(
            model_name='usercredential',
            name='userEmail',
            field=models.CharField(default=None, max_length=40, primary_key=True, serialize=False),
        ),
    ]
