# Generated by Django 4.1 on 2022-08-11 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuizoPedia', '0004_remove_usercredential_userid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionAnswers',
            fields=[
                ('questionId', models.AutoField(primary_key=True, serialize=False)),
                ('questionDescription', models.CharField(default='', max_length=200)),
                ('option1', models.CharField(default='', max_length=200)),
                ('option2', models.CharField(default='', max_length=200)),
                ('option3', models.CharField(default='', max_length=200)),
                ('option4', models.CharField(default='', max_length=200)),
                ('correctAnswer', models.CharField(default='', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='UserAttemptHistory',
            fields=[
                ('attemptId', models.AutoField(primary_key=True, serialize=False)),
                ('userEmail', models.CharField(default=None, max_length=40)),
                ('userAttendedQuestions', models.CharField(default=None, max_length=20)),
                ('userGainedGrades', models.FloatField(default=0, max_length=10)),
                ('dateOnWhichAttempted', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
